DEEPSORT:
  REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 10000000
  MIN_CONFIDENCE: 0.05
  NMS_MAX_OVERLAP: 1000000
  MAX_IOU_DISTANCE: 1
  MAX_AGE: 100000000
  N_INIT: 1
  NN_BUDGET: 10000000
  
